{% set name = "emval" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/emval-{{ version }}.tar.gz
  sha256: 7ed6188c00acaffa6ccd3125c752fa4a64c0f1045bfd628fea5add156928f500

build:
  skip: True  # [py<38]
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.7,<2.0
    - pip
  run:
    - python

test:
  imports:
    - emval
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bnkc/emval
  summary: Blazingly fast email validator.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - thewchan
