{% set name = "emval" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/emval-{{ version }}.tar.gz
  sha256: f22f8c0670503631a3fada34516b6d9b1498ab3eeff9a572b09172d3b54ede67

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - set PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1  # [win]
    - export PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1  # [unix]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.7,<2.0
    - pip
  run:
    - python

test:
  imports:
    - emval
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bnkc/emval
  summary: Blazingly fast email validator.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - thewchan
